### Test /login
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpass"
}

### Test /checkout
POST http://localhost:3000/checkout
Content-Type: application/json

{
  "username": "testuser",
  "cart": [
    { "name": "Carrots", "price": 20 },
    { "name": "Potatoes", "price": 15 }
  ]
}
